print ('#criando uma pagina html')
print("Gera html index")
pagina = open("Index.html","w", encoding="utf-8")
pagina.write("<!DOCTYPE HTML>\n <Html>\n")
pagina.write("      <HEAD>\n")
pagina.write("          <Title>Ola Python no Html - Gledson Oliveira Big Blue IT </Title>\n")
pagina.write("      </HEAD>\n")
pagina.write("      <Body>\n")
pagina.write("      <h1>Controle de Informacoes <br>\n")
pagina.write("        Aqui sera gerado informacoes pertinentes ao banco de dados ou de alguma API<br>  \n")
pagina.write("         Com esse gerador ficara claro como podemos ajudar a melhorar a produtividade <br> \n")

pagina.write("      Com anos de esperiencias em negocios e implantacoes em ti <br>\n")
pagina.write("      Fica claro que com um bom entendimento e tecnologias podemos atende de ponta a ponta o processo\n")
pagina.write("      <h2> Projetos <br>\n")
pagina.write("      <h2> - Devops - Suporte - Ensinar a adotar a Cultura  <br>\n")

pagina.write("      </Body>\n")
pagina.write("</Html>\n")
pagina.flush()
pagina.close()
